import { Metadata } from "next";
import Header from "@/components/home/header/Header";
import Banner from "@/components/home/banner/Banner";
import requests from "@/utils/requests";
import Row from "@/components/home/row/Row";
import ModalData from "@/components/home/ModalData";

export const metadata: Metadata = {
  title: "Home - Netflix",
  description: "Generated by create next app",
  icons: {
    icon: "favicon.ico",
  },
};

export default async function Home() {
  const [
    netflixOriginals,
    trendingNow,
    topRated,
    actionMovies,
    comedyMovies,
    horrorMovies,
    romanceMovies,
    animationMovies,
  ] = await Promise.all([
    fetch(requests.fetchNetflixOriginals, { next: { revalidate: 600 } }).then(
      (res) => res.json()
    ),
    fetch(requests.fetchTrending, { next: { revalidate: 600 } }).then((res) =>
      res.json()
    ),
    fetch(requests.fetchTopRated, { next: { revalidate: 600 } }).then((res) =>
      res.json()
    ),
    fetch(requests.fetchActionMovies, { next: { revalidate: 600 } }).then(
      (res) => res.json()
    ),
    fetch(requests.fetchComedyMovies, { next: { revalidate: 600 } }).then(
      (res) => res.json()
    ),
    fetch(requests.fetchHorrorMovies, { next: { revalidate: 600 } }).then(
      (res) => res.json()
    ),
    fetch(requests.fetchRomanceMovies, { next: { revalidate: 600 } }).then(
      (res) => res.json()
    ),
    fetch(requests.fetchAnimationMovies, { next: { revalidate: 600 } }).then(
      (res) => res.json()
    ),
  ]);

  return (
    <div className="relative h-screen bg-gradient-to-b lg:h-[140vh]">
      <Header />
      <main className="relative pl-4 pb-24 lg:space-y-24 lg:pl-16">
        <Banner netflixOriginals={netflixOriginals.results} />
        <section className="md:space-y-24">
          <Row title="Trending Now" movies={trendingNow.results} />
          <Row title="Top Rated" movies={topRated.results} />
          <Row title="Comedies" movies={comedyMovies.results} />
          <Row title="Action" movies={actionMovies.results} />
          <Row title="Scary Movies" movies={horrorMovies.results} />
          <Row title="Romance Movies" movies={romanceMovies.results} />
          <Row title="Animated Movies" movies={animationMovies.results} />
        </section>
      </main>
      <ModalData />
    </div>
  );
}
