import { Metadata } from 'next'
import Header from '@/components/Header'
import Banner from '@/components/Banner'
import requests from '@/utils/requests'
import Row from '@/components/Row'

export const metadata: Metadata = {
  title: 'Home - Netflix',
  description: 'Generated by create next app',
  icons: {
    icon: 'favicon.ico'
  }
}

export default async function Home() {

  const [
    netflixOriginals,
    trendingNow,
    topRated,
    actionMovies,
    comedyMovies,
    horrorMovies,
    romanceMovies,
    animationMovies,
  ] = await Promise.all([
    fetch(requests.fetchNetflixOriginals).then((res) => res.json()),
    fetch(requests.fetchTrending).then((res) => res.json()),
    fetch(requests.fetchTopRated).then((res) => res.json()),
    fetch(requests.fetchActionMovies).then((res) => res.json()),
    fetch(requests.fetchComedyMovies).then((res) => res.json()),
    fetch(requests.fetchHorrorMovies).then((res) => res.json()),
    fetch(requests.fetchRomanceMovies).then((res) => res.json()),
    fetch(requests.fetchAnimationMovies).then((res) => res.json()),
  ])

  return (
    <div className='relative h-screen bg-gradient-to-b lg:h-[140vh]'>
    <Header/>
    <main className="relative pl-4 pb-24 lg:space-y-24 lg:pl-16">
      <Banner netflixOriginals={netflixOriginals.results}/>
      <section className="md:space-y-24">
        <Row title="Trending Now" movies={trendingNow.results}/>
        <Row title="Top Rated" movies={topRated.results}/>
        <Row title="Comedies" movies={comedyMovies.results}/>
        <Row title="Action" movies={actionMovies.results}/>
        <Row title="Scary Movies" movies={horrorMovies.results}/>
        <Row title="Romance Movies" movies={romanceMovies.results}/>
        <Row title="Animated Movies" movies={animationMovies.results}/>
      </section>
    </main>
    {/* Modal */}
    </div>
  )
}
